type: GeneralStereo
name: kitti360_test0

args:
  # NOTE: container path, not host
  root: /workspace/ASP/data/data_2d_test_slam/test_0/2013_05_28_drive_0008_sync

  camera:
    fx: 552.554261
    fy: 552.554261
    cx: 682.049453
    cy: 238.769549

  bl: 0.594052
  format: png
